T = int(input())
for i in range(0,T):
    r0, c0 = map(int,input().split())
    if r0==1 and c0==1:
        print('39')
        print('1 1')
        print('2 2')
        print('1 3')
        print('2 4')
        print('1 5')
        print('2 6')
        print('1 7')
        print('2 8')
        print('4 6')
        print('3 5')
        print('4 4')
        print('3 3')
        print('4 2')
        print('3 1')
        print('4 2')
        print('5 1')
        print('6 2')
        print('5 3')
        print('6 4')
        print('5 5')
        print('6 6')
        print('4 8')
        print('5 7')
        print('6 8')
        print('7 7')
        print('8 8')
        print('7 7')
        print('8 6')
        print('7 5')
        print('8 4')
        print('7 3')
        print('8 2')
        print('7 1')